name: bright_minds
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  fluttertoast: ^8.2.12
  get_it: ^8.0.3
  go_router: ^15.1.1
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.4
  url_launcher: ^6.3.1
  dartz: ^0.10.1
  dynamic_path_url_strategy: ^1.0.0
  video_player: ^2.9.5
  chewie: ^1.11.3
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-VariableFont_wdth,wght.ttf
    - family: NunitoSans
      fonts:
        - asset: assets\fonts\NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf

flutter_native_splash:
  color: '#f2ffff'
  image: assets/images/logo.png

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_assets.dart