abstract class AppStrings {
  static const String appName = 'Bright Minds',
      email = 'Email',
      password = 'Password',
      confirmPassword = 'Confirm Password',
      forgotPassword = 'Forgot Password?',
      login = 'Login',
      checkingInProgress = 'Checking in progress',
      dontHaveAccount = 'Don\'t have account? ',
      alreadyHaveAccount = 'Already have account? ',
      loginNow = 'Login Now',
      register = 'Register',
      firstName = 'First Name',
      lastName = 'Last Name',
      createNewPassword = 'Create New Password',
      newPassword = 'New Password',
      yourNewPassword =
          'Your new password must be different from the previously used passwords',
      enterEmail = 'Enter Your Email',
      willSendMessage = 'Will Send Verify Email For You',
      phoneNumber = 'Phone Number',
      pleaseCheckEmail = 'Please Check Your Email For Verify',
      sendEmail = 'Send Email',
      wellcom = 'Wellcom',
      instructors = 'Instructors',
      courses = 'Courses',
      skilledInstructors = 'Skilled Instructors',
      dimaElitr =
          'Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam',
      onlineClasses = 'Online Classes',
      homeProjects = 'Home Projects',
      bookLibrary = 'Book Library',
      internationalCerificate = 'International Certificate',
      popularCourses = 'Popular Courses',
      price = 'Price',
      expertInstructors = 'Expert Instructors',
      addToBag = 'Add To Bag',
      buy = 'Buy',
      skip = 'Skip',
      thisFieldCannotBeEmpty = 'This field cannot be empty',
      myBag = 'My Bag',
      myCrt = 'My Cart',
      done = 'Done',
      logOut = 'Log Out',
      delete = 'Delete',
      edit = 'Edit',
      payment = 'Payment',
      oldPassword = 'Old Password',
      changePassword = 'Change Password',
      couldNotLaunch = 'Could not launch',
      commint = 'Commint',
      addCommint = 'Add Commint',
      evaluation = 'Evaluation:',
      cancel = 'Cancel',
      submmit = 'Submmit',
      compleatPurchase = 'Please check the cart to complete the purchase',
      firstBuyCourse = 'First, buy the course',
      wellcomToBright = 'Welcome To Bright Minds',
      boardingSub1 =
          'Discover a World of knowledge at your fingertips with \'Bright Minds\' comprehensive learning platform',
      boardingSub2 =
          'Access high-quality courses from top educators and industry experts, anytime, anywhere',
      learnFromBeast = 'Learn From The Best',
      youCanWathc = 'You can watch the course',
      errorTryAgain = 'An error occurred, please try again',
      next = 'Next';
}
