abstract class AppStrings {
  static const String appName = 'Bright Minds',
      email = 'Email',
      password = 'Password',
      confirmPassword = 'Confirm Password',
      forgotPassword = 'Forgot Password?',
      login = 'Login',
      dontHaveAccount = 'Don\'t have account? ',
      alreadyHaveAccount = 'Already have account? ',
      signUp = 'Sign Up',
      signIn = 'Sign In',
      register = 'Register',
      firstName = 'First Name',
      lastName = 'Last Name',
      createNewPassword = 'Create New Password',
      newPassword = 'New Password',
      yourNewPassword =
          'Your new password must be different from the previously used passwords',
      enterEmail = 'Enter Your Email',
      willSendMessage = 'Will Send Verify Email For You',
      phoneNumber = 'Phone Number',
      successResetPassword = 'Success Reset Password!',
      pleaseCheckEmail = 'Please Check Your Email For Verify',
      sendEmail = 'Send Email',
      verifyDone = 'Verify Done! Login Now',
      wellcom = 'Wellcom',
      unexpectedError = 'Unexpected error occurred',
      instructors = 'Instructors',
      courses = 'Courses',
      temporErate =
          'Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet',
      temporErateAtClita =
          'Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit.',
      aboutUs = 'About Us',
      wellcomTo = 'Wellcom to BRIGHT MINDS',
      popularCourses = 'Popular Courses',
      price = 'Price',
      contact = 'Contact',
      contactForAny = 'Contact For Any Query',
      getInToutch = 'Get In Toutch',
      theContactForm =
          'The contact form is currently inactive. Get a functional and working contact form with Ajax & PHP in a few minutes. Just copy and paste the files, add a little code and you\'re done. ',
      tanta = 'Tanta',
      mobile = 'Mobile',
      mobileNumbe = '+012 34567 890',
      emailExample = 'info@example.com',
      contactUs = 'Contact Us',
      clientName = 'Client Name',
      ourStudentsSay = 'Our Students Say!',
      testimonial = 'Testimonial',
      name = 'Name',
      message = 'Message',
      send = 'Send',
      subject = 'Subject',
      expertInstructors = 'Expert Instructors',
      addToCart = 'Add To Cart',
      buyNow = 'Buy Now',
      skip = 'Skip',
      thisFieldCannotBeEmpty = 'This field cannot be empty',
      myDetails = 'My Details',
      myCourses = 'My Courses',
      logOut = 'Log Out',
      deleteAccount = 'Delete Account',
      edit = 'Edit',
      payment = 'Payment',
      next = 'Next';
}
