abstract class RouteKeys {
  static const String onBoarding = '/onboarding',
      login = '/login',
      register = '/register',
      forgotPassword = '/forgot-password',
      resetPassword = '/reset-password',
      home = '/home',
      course = '/course',
      courseDetails = '/course-details',
      video = '/video',
      videoPlay = '/video-play',
      instructor = '/instructor',
      instructorDetails = '/instructor-details',
      profile = '/profile',
      editProfile = '/edit-profile',
      cart = '/cart',
      bag = '/bag',
      userCourseDetails = '/user-course-details',
      contact = '/contact';
}
